import time
from typing import Dict, Any, Optional


demo_query_1 = "Show charges only for a person with race=white, length_of_stay=4, discharge_year=2023, age_group=30-49, apr_severity_of_illness_description=Minor and payment_typology_1=Blue Cross/Blue Shield."

demo_query_2 = "Show charges, costs and cost differential projection for an expecting mother with race=Black/African American and Other Race, length_of_stay from 1 to 5, discharge_year between 2021 to 2023, age_group=30-49, apr_severity_of_illness_description=Minor, payment_typology_1=Blue Cross/Blue Shield and hospital_county=Kings. Display data by discharge_year and length_of_stay."

demo_outcome1 = {
    "summary": "The XGBoost model predicts a total discharge charge of $31,591.80 for the specified patient profile. This prediction is based on a 2023 discharge year, a patient in the 30-49 age group, White race, with a 4-day length of stay, minor severity of illness, and Blue Cross/Blue Shield as the payment typology. The moderate length of stay (4 days) combined with minor illness severity suggests a relatively standard hospitalization case. The Blue Cross/Blue Shield payment type is a common private insurance category that may influence the charge distribution based on negotiated rates and coverage patterns reflected in the training data.",
    "table": [
        {
            "discharge_year": 2023,
            "age_group": "30-49",
            "race": "White",
            "length_of_stay": 4,
            "apr_severity_of_illness_description": "Minor",
            "payment_typology_1": "Blue Cross/Blue Shield",
            "charge": 31591.80,
        }
    ],
    "graph": {
        "data": [
            {
                "x": ["Charge"],
                "y": [31591.80],
                "type": "bar",
                "name": "Predicted Charge",
                "marker": {"color": "steelblue"},
            }
        ],
        "layout": {
            "title": "Predicted Charge for Patient Profile (2023)",
            "xaxis": {"title": "Metric"},
            "yaxis": {"title": "Amount ($)"},
            "showlegend": True,
        },
    },
}

demo_outcome2 = {
    "summary": "This comprehensive analysis examines healthcare charges, costs, and cost differential projections for expecting mothers aged 30-49 with Minor illness severity, Blue Cross/Blue Shield insurance, in Kings County hospitals across discharge years 2021-2023 and length of stay 1-5 days for two race categories (Black/African American and Other Race). Charges range from $14,044.76 (2023, LOS=1, Other Race) to $44,875.21 (2022, LOS=5, Black/African American), showing a clear positive correlation with length of stay. Costs range from $5,505.32 to $20,760.40, following similar patterns but at significantly lower absolute values. All cost differentials are negative, ranging from -$7,271.20 to -$24,246.69, indicating that charges consistently exceed costs by substantial margins (approximately 49-66% markup). Year-over-year trends show modest charge increases from 2021 to 2023, with 2022 showing the highest charges for longer stays. Black/African American patients show slightly higher charges than Other Race patients at shorter stays (LOS 1-2), but this pattern reverses at longer stays (LOS 4-5). The XGBoost model's tree-split impacts reveal that length of stay is the dominant cost driver, followed by discharge year, with race having minimal differential impact on predictions.",
    "table": [
        {
            "discharge_year": 2021,
            "length_of_stay": 1,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 14541.77,
            "cost": 5673.91,
            "diff_cost": -7393.37,
        },
        {
            "discharge_year": 2021,
            "length_of_stay": 1,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 14177.76,
            "cost": 5830.36,
            "diff_cost": -7271.20,
        },
        {
            "discharge_year": 2021,
            "length_of_stay": 2,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 17733.20,
            "cost": 8382.67,
            "diff_cost": -11858.23,
        },
        {
            "discharge_year": 2021,
            "length_of_stay": 2,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 17460.24,
            "cost": 8194.77,
            "diff_cost": -11994.41,
        },
        {
            "discharge_year": 2021,
            "length_of_stay": 3,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 29043.64,
            "cost": 10981.74,
            "diff_cost": -18631.46,
        },
        {
            "discharge_year": 2021,
            "length_of_stay": 3,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 28444.63,
            "cost": 11012.71,
            "diff_cost": -18132.80,
        },
        {
            "discharge_year": 2021,
            "length_of_stay": 4,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 29167.77,
            "cost": 12153.56,
            "diff_cost": -19978.76,
        },
        {
            "discharge_year": 2021,
            "length_of_stay": 4,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 29831.78,
            "cost": 12632.29,
            "diff_cost": -20641.44,
        },
        {
            "discharge_year": 2021,
            "length_of_stay": 5,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 38535.05,
            "cost": 14873.87,
            "diff_cost": -18838.75,
        },
        {
            "discharge_year": 2021,
            "length_of_stay": 5,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 38213.95,
            "cost": 15178.29,
            "diff_cost": -21718.76,
        },
        {
            "discharge_year": 2022,
            "length_of_stay": 1,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 16080.34,
            "cost": 5571.08,
            "diff_cost": -9195.12,
        },
        {
            "discharge_year": 2022,
            "length_of_stay": 1,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 15163.23,
            "cost": 5505.32,
            "diff_cost": -9113.61,
        },
        {
            "discharge_year": 2022,
            "length_of_stay": 2,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 21261.26,
            "cost": 7997.07,
            "diff_cost": -13039.81,
        },
        {
            "discharge_year": 2022,
            "length_of_stay": 2,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 20475.53,
            "cost": 7729.07,
            "diff_cost": -13216.67,
        },
        {
            "discharge_year": 2022,
            "length_of_stay": 3,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 28367.78,
            "cost": 11303.04,
            "diff_cost": -18764.48,
        },
        {
            "discharge_year": 2022,
            "length_of_stay": 3,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 27335.18,
            "cost": 11245.77,
            "diff_cost": -18152.87,
        },
        {
            "discharge_year": 2022,
            "length_of_stay": 4,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 34822.95,
            "cost": 13738.23,
            "diff_cost": -23434.12,
        },
        {
            "discharge_year": 2022,
            "length_of_stay": 4,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 34929.23,
            "cost": 14101.25,
            "diff_cost": -24246.69,
        },
        {
            "discharge_year": 2022,
            "length_of_stay": 5,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 44875.21,
            "cost": 16553.97,
            "diff_cost": -22833.93,
        },
        {
            "discharge_year": 2022,
            "length_of_stay": 5,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 44752.56,
            "cost": 17570.96,
            "diff_cost": -24237.30,
        },
        {
            "discharge_year": 2023,
            "length_of_stay": 1,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 15566.32,
            "cost": 6243.96,
            "diff_cost": -10854.50,
        },
        {
            "discharge_year": 2023,
            "length_of_stay": 1,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 14044.76,
            "cost": 6440.17,
            "diff_cost": -10066.54,
        },
        {
            "discharge_year": 2023,
            "length_of_stay": 2,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 20772.04,
            "cost": 9288.59,
            "diff_cost": -13917.91,
        },
        {
            "discharge_year": 2023,
            "length_of_stay": 2,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 19429.09,
            "cost": 9282.58,
            "diff_cost": -13327.14,
        },
        {
            "discharge_year": 2023,
            "length_of_stay": 3,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 28218.01,
            "cost": 13185.47,
            "diff_cost": -19467.73,
        },
        {
            "discharge_year": 2023,
            "length_of_stay": 3,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 26488.04,
            "cost": 13491.37,
            "diff_cost": -18140.41,
        },
        {
            "discharge_year": 2023,
            "length_of_stay": 4,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 33594.59,
            "cost": 16097.08,
            "diff_cost": -23388.19,
        },
        {
            "discharge_year": 2023,
            "length_of_stay": 4,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 31899.39,
            "cost": 16726.66,
            "diff_cost": -23477.92,
        },
        {
            "discharge_year": 2023,
            "length_of_stay": 5,
            "age_group": "30-49",
            "race": "Black/African American",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 42975.68,
            "cost": 19417.41,
            "diff_cost": -22958.87,
        },
        {
            "discharge_year": 2023,
            "length_of_stay": 5,
            "age_group": "30-49",
            "race": "Other Race",
            "apr_severity": "Minor",
            "payment_typology": "Blue Cross/Blue Shield",
            "hospital_county": "Kings",
            "charge": 40993.98,
            "cost": 20760.40,
            "diff_cost": -23079.15,
        },
    ],
    "graph": {
        "data": [
            {
                "type": "bar",
                "name": "Charges - Black/African American",
                "x": [
                    "2021-LOS1",
                    "2021-LOS2",
                    "2021-LOS3",
                    "2021-LOS4",
                    "2021-LOS5",
                    "2022-LOS1",
                    "2022-LOS2",
                    "2022-LOS3",
                    "2022-LOS4",
                    "2022-LOS5",
                    "2023-LOS1",
                    "2023-LOS2",
                    "2023-LOS3",
                    "2023-LOS4",
                    "2023-LOS5",
                ],
                "y": [
                    14541.77,
                    17733.20,
                    29043.64,
                    29167.77,
                    38535.05,
                    16080.34,
                    21261.26,
                    28367.78,
                    34822.95,
                    44875.21,
                    15566.32,
                    20772.04,
                    28218.01,
                    33594.59,
                    42975.68,
                ],
                "marker": {"color": "#1f77b4"},
            },
            {
                "type": "bar",
                "name": "Charges - Other Race",
                "x": [
                    "2021-LOS1",
                    "2021-LOS2",
                    "2021-LOS3",
                    "2021-LOS4",
                    "2021-LOS5",
                    "2022-LOS1",
                    "2022-LOS2",
                    "2022-LOS3",
                    "2022-LOS4",
                    "2022-LOS5",
                    "2023-LOS1",
                    "2023-LOS2",
                    "2023-LOS3",
                    "2023-LOS4",
                    "2023-LOS5",
                ],
                "y": [
                    14177.76,
                    17460.24,
                    28444.63,
                    29831.78,
                    38213.95,
                    15163.23,
                    20475.53,
                    27335.18,
                    34929.23,
                    44752.56,
                    14044.76,
                    19429.09,
                    26488.04,
                    31899.39,
                    40993.98,
                ],
                "marker": {"color": "#aec7e8"},
            },
            {
                "type": "bar",
                "name": "Costs - Black/African American",
                "x": [
                    "2021-LOS1",
                    "2021-LOS2",
                    "2021-LOS3",
                    "2021-LOS4",
                    "2021-LOS5",
                    "2022-LOS1",
                    "2022-LOS2",
                    "2022-LOS3",
                    "2022-LOS4",
                    "2022-LOS5",
                    "2023-LOS1",
                    "2023-LOS2",
                    "2023-LOS3",
                    "2023-LOS4",
                    "2023-LOS5",
                ],
                "y": [
                    5673.91,
                    8382.67,
                    10981.74,
                    12153.56,
                    14873.87,
                    5571.08,
                    7997.07,
                    11303.04,
                    13738.23,
                    16553.97,
                    6243.96,
                    9288.59,
                    13185.47,
                    16097.08,
                    19417.41,
                ],
                "marker": {"color": "#2ca02c"},
            },
            {
                "type": "bar",
                "name": "Costs - Other Race",
                "x": [
                    "2021-LOS1",
                    "2021-LOS2",
                    "2021-LOS3",
                    "2021-LOS4",
                    "2021-LOS5",
                    "2022-LOS1",
                    "2022-LOS2",
                    "2022-LOS3",
                    "2022-LOS4",
                    "2022-LOS5",
                    "2023-LOS1",
                    "2023-LOS2",
                    "2023-LOS3",
                    "2023-LOS4",
                    "2023-LOS5",
                ],
                "y": [
                    5830.36,
                    8194.77,
                    11012.71,
                    12632.29,
                    15178.29,
                    5505.32,
                    7729.07,
                    11245.77,
                    14101.25,
                    17570.96,
                    6440.17,
                    9282.58,
                    13491.37,
                    16726.66,
                    20760.40,
                ],
                "marker": {"color": "#98df8a"},
            },
            {
                "type": "bar",
                "name": "Cost Differential - Black/African American",
                "x": [
                    "2021-LOS1",
                    "2021-LOS2",
                    "2021-LOS3",
                    "2021-LOS4",
                    "2021-LOS5",
                    "2022-LOS1",
                    "2022-LOS2",
                    "2022-LOS3",
                    "2022-LOS4",
                    "2022-LOS5",
                    "2023-LOS1",
                    "2023-LOS2",
                    "2023-LOS3",
                    "2023-LOS4",
                    "2023-LOS5",
                ],
                "y": [
                    -7393.37,
                    -11858.23,
                    -18631.46,
                    -19978.76,
                    -18838.75,
                    -9195.12,
                    -13039.81,
                    -18764.48,
                    -23434.12,
                    -22833.93,
                    -10854.50,
                    -13917.91,
                    -19467.73,
                    -23388.19,
                    -22958.87,
                ],
                "marker": {"color": "#d62728"},
            },
            {
                "type": "bar",
                "name": "Cost Differential - Other Race",
                "x": [
                    "2021-LOS1",
                    "2021-LOS2",
                    "2021-LOS3",
                    "2021-LOS4",
                    "2021-LOS5",
                    "2022-LOS1",
                    "2022-LOS2",
                    "2022-LOS3",
                    "2022-LOS4",
                    "2022-LOS5",
                    "2023-LOS1",
                    "2023-LOS2",
                    "2023-LOS3",
                    "2023-LOS4",
                    "2023-LOS5",
                ],
                "y": [
                    -7271.20,
                    -11994.41,
                    -18132.80,
                    -20641.44,
                    -21718.76,
                    -9113.61,
                    -13216.67,
                    -18152.87,
                    -24246.69,
                    -24237.30,
                    -10066.54,
                    -13327.14,
                    -18140.41,
                    -23477.92,
                    -23079.15,
                ],
                "marker": {"color": "#ff9896"},
            },
        ],
        "layout": {
            "title": "Healthcare Charges, Costs & Cost Differential by Discharge Year, Length of Stay, and Race",
            "xaxis": {"title": "Discharge Year - Length of Stay", "tickangle": -45},
            "yaxis": {"title": "Amount ($)"},
            "barmode": "group",
            "legend": {"orientation": "h", "y": -0.3},
            "height": 600,
            "margin": {"b": 150},
        },
    },
}


def json_content_outcome(query: str) -> Optional[Dict[str, Any]]:
    if query.casefold() == demo_query_1.casefold():
        time.sleep(5)
        return demo_outcome1
    elif query.casefold() == demo_query_2.casefold():
        time.sleep(15)
        return demo_outcome2
    else:
        return None
